version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: jobby-mongo
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

  mongo-init-replica:
    image: mongo:7
    depends_on:
      mongo:
        condition: service_started
    entrypoint: >
      bash -c "
        echo 'Esperando a que Mongo estÃ© listo...' &&
        for i in {1..15}; do
          mongosh --host mongo:27017 --eval 'db.runCommand({ ping: 1 })' &> /dev/null && break;
          echo 'Esperando...';
          sleep 1;
        done;

        echo 'Inicializando Replica Set...' &&
        mongosh --host mongo:27017 --eval '
          if (!rs.status().ok) {
            rs.initiate({
              _id: \"rs0\",
              members: [{ _id: 0, host: \"mongo:27017\" }]
            });
          }
        ';
      "
    restart: "no"

volumes:
  mongo_data:
